"""Adds exercise_name column to models.py

Revision ID: 56a01a85f0ae
Revises: 9bc1d35342f4
Create Date: 2023-08-22 10:45:30.035158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56a01a85f0ae'
down_revision: Union[str, None] = '9bc1d35342f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise', sa.Column('exercise_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise', 'exercise_name')
    # ### end Alembic commands ###
