"""Adds back_populates='exercise' to the Exercise class and back_populates='workout' to the Workout class

Revision ID: 691f329f5db9
Revises: 56a01a85f0ae
Create Date: 2023-08-22 14:17:29.575827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '691f329f5db9'
down_revision: Union[str, None] = '56a01a85f0ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
