"""Revises models.py

Revision ID: 9bc1d35342f4
Revises: c446f34cd853
Create Date: 2023-08-22 10:31:41.396375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bc1d35342f4'
down_revision: Union[str, None] = 'c446f34cd853'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_description', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('units', sa.String(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_name', sa.String(), nullable=True),
    sa.Column('workout_description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_exercise',
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.Column('workout_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], )
    )
    op.drop_table('exercises')
    op.drop_table('workouts')
    op.drop_table('workout_exercises')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_exercises',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('workout_id', sa.INTEGER(), nullable=True),
    sa.Column('exercise_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workouts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('workout_name', sa.VARCHAR(), nullable=True),
    sa.Column('wortout_description', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercises',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('exercise_description', sa.VARCHAR(), nullable=True),
    sa.Column('category', sa.VARCHAR(), nullable=True),
    sa.Column('weight', sa.INTEGER(), nullable=True),
    sa.Column('units', sa.VARCHAR(), nullable=True),
    sa.Column('reps', sa.INTEGER(), nullable=True),
    sa.Column('sets', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('workout_exercise')
    op.drop_table('workout')
    op.drop_table('exercise')
    # ### end Alembic commands ###
