"""Changes the'exercises' attribute in the Exercise class to 'exercise'.

Revision ID: d46871cb93ad
Revises: 691f329f5db9
Create Date: 2023-08-22 14:36:27.759455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd46871cb93ad'
down_revision: Union[str, None] = '691f329f5db9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
